config/routes.rb
Rails.application.routes.draw do
  root to: 'pets#index'
  get 'pets/random', to: 'pets#random', as: 'random'
  resources :pets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
    enum animal: { cat: 0, dog: 1, other: 2 }
    has_one_attached :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_animal, only: [:new, :edit]
    
    def index
      @pets = Pet.all
  end

  def show
      @pet = Pet.find(params[:id])
  end

  def new
      @pet = Pet.new
  end

  def create
      @pet = Pet.new(pet_params)
      @pet.save

      flash.notice = "Pet '#{@pet.name}' Created!"

      redirect_to pet_path(@pet)
  end

  def destroy
      @pet = Pet.find(params[:id])
      @pet.destroy     

      flash.notice = "Pet '#{@pet.name}' Deleted!"

      redirect_to pets_path
  end

  def edit
      @pet = Pet.find(params[:id])
  end

  def update
      @pet = Pet.find(params[:id])
      @pet.update(pet_params)

      flash.notice = "Pet '#{@pet.name}' Updated!"

      redirect_to pet_path(@pet)        
  end

  def random
    @random = Pet.offset(rand(Pet.count)).first
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :animal, :bio, :picture)
  end

  def set_animal
    @animal_types = Pet.animals.keys
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | SharePets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= render "shared/nav" %>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/pets/edit.html.erb
<% provide(:title, "Edit") %>

<h1>Edit Your Pet Details</h1>

<%= render 'shared/form' %>

app/views/pets/index.html.erb
<% provide(:title, "Home") %>

<ul id="pets">
    <% @pets.each do | pet | %>
        <li>
            <%= link_to pet.name, pet_path(pet) %>
            <br>
            <%= image_tag pet.picture if pet.picture.attached? %>
        </li>
    <% end %>
</ul>

app/views/pets/new.html.erb
<% provide(:title, "Add Your Pet") %>

<%= render 'shared/form' %>

app/views/pets/random.html.erb
<% provide(:title, "Random") %>

<h1><%= @random.name %></h1>
<%= image_tag @random.picture if @random.picture.attached? %>
<p><%= @random.animal.capitalize %></p>
<h5>Bio:</h5>
<p><%= @random.bio %></p>

<%= link_to "<< Back to Pet List", pets_path %>

app/views/pets/show.html.erb
<% provide(:title, @pet.name) %>

<h1><%= @pet.name %></h1>
<%= image_tag @pet.picture if @pet.picture.attached? %>
<p><%= @pet.animal.capitalize %></p>
<h5>Bio:</h5>
<p><%= @pet.bio %></p>

<%= link_to "Edit", edit_pet_path(@pet) %>
<%= link_to "Delete", pet_path(@pet), method: :delete, data: {confirm: "Really delete the pet?"} %>
<br>
<%= link_to "<< Back to Pet List", pets_path %>

app/views/shared/_footer.html.erb
  <footer id="footer" class="mt-2 py-4 bg-light text-grey-50">
    <div class="container text-center">
      <small>&copy; 2020 SharePets      
      <div class="text-right">
        <a href="#top">Back to top</a>
      </div>
      </small>

    </div>

  </footer>

app/views/shared/_form.html.erb
<%= form_for(@pet, html: {multipart: true}) do |f| %>
    <ul>
    <% @pet.errors.full_messages.each do |error| %>
        <li><%= error %></li>
    <% end %>
    </ul>
    <p>
        <%= f.label :name %>
        <br>
        <%= f.text_field :name %>
    </p>
        <p>Type of animal</p>
        <% @animal_types.each do |option| %>
        <%= f.label option %>
        <%= f.radio_button :animal, option %>
    <% end %>
    <p>
        <%= f.label :bio %>
        <br>
        <%= f.text_field :bio %>
    </p>
    <p>
        <%= image_tag @pet.picture if @pet.picture.attached? %>
    </p>
    <p>
        <%= f.label :picture %> 
        <br>
        <%= f.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/shared/_header.html.erb
    <div id="top" class="text-center jumbotron">
      <h1 class="display-4">Share Pets!</h1>
      <p class="lead">This is a tag line.</p>
    </div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item active nav-link">
          <%= link_to("Home", root_path) %>
        </li>
        <li class="nav-item active nav-link">
          <%= link_to("Search", root_path) %>
        </li>
        <li class="nav-item active nav-link">
          <%= link_to("Random Pet", random_path(@random)) %>
        </li>
        <li class="nav-item active nav-link">
          <%= link_to("Add Your Pet", new_pet_path) %>
        </li>
      </ul>
    </div>
  </nav>